### PR TITLE
Enable clang-tidy readability-braces-around-statements check

### PR DESCRIPTION
**Pull request by skrobinson**
All tests still pass.

Signed-off-by: Sean Robinson <sean.robinson@scottsdalecc.edu>

### CODE REVIEW

**Comment by skrobinson** [comment]
@p-ranav 

I had hoped #159 could be completed and merged before this PR to reduce the work needed to prepare #159 for inclusion, but I do not want to wait any longer.

So, I'm ready for feedback about changes needed to make this branch acceptable for merge.

**Comment by wanjiadenghuo111** [comment]
亲，来信已经收到！祝你快乐！

**Comment by p-ranav** [comment]
Thanks @skrobinson 

I get three warnings about `constexpr variable` naming. Did you get these as well?

image

Looks like they are coming from:

* `readability-identifier-naming.ConstexprVariableCase = lower_case`
* `readability-identifier-naming.StructIgnoredRegexp = "parse_number"` doesn't seem to work for me?

**Comment by skrobinson** [comment]
Interesting... What version of `clang-tidy` are you using?

`*IgnoredRegexp` suppressions look to have been added in clang-tidy v12, which is the version used by `StaticAnalysis`. I have not seen these warnings since adding the ignore patterns.

**Comment by p-ranav** [comment]
I see! The `clang-tidy` version I have is `10.0.0`. That would explain it. 

```console
foo:bar$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0

  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: icelake-client
```

I have no other concerns. I'll merge this. Thanks!!

**Pull request merged**
