### PR TITLE
Fix std::min conflict with min/max definitions from windows.h

### PR DESCRIPTION
**Pull request by Chuvi-w**

### CODE REVIEW

**Comment by skrobinson** [comment]
What about `std::min<size_t>`?  Does specifying a type stop the macro replacement on Windows?

**Comment by Chuvi-w** [comment]
Seems that specifying a type also works well.

**Comment by skrobinson** [comment]
I agree about a type change.  But in this case the type is `size_t`, which is unlikely to change soon.

Another option woud be `std::min<decltype(std::declval<T>().size())>`.  Then the type would be correct for any container T with a size function.

**Comment by Chuvi-w** [comment]
I've thought about decltype.
But it looks llike... a bit overprinted.

**Comment by Bedzior** [comment]
Hi, my two cents: I guess `std::size_t` is more appropriate in a C++ library.

**Comment by skrobinson** [comment]
@Bedzior

Yes, you're right.  I copied `size_t` from the definition of `repr_max_container_size`, but `std::size_t` is more correct.

Looking through the rest of the file, there is an opportunity for someone to convert many `size_t`.

**Comment by Chuvi-w** [comment]
Ok, but  replacing size_t to std::size_t is not purpose of this PR.
Can you take it like this, and then somehow add std :: to the types?

**Comment by Chuvi-w** [comment]
Thanks

**Pull request merged**
