### PR TITLE
Add StaticAnalysis PR Action

### PR DESCRIPTION
**Pull request by skrobinson**
Matches clang-tidy to current sources and fixes the few minor cppcheck style warning.

### CODE REVIEW

**Comment by skrobinson** [comment]
This PR is running into a problem with permissions/credentials when the added Action tries to post a comment to the repo. I've included the relevant portion of the log.

This may take a few weeks to solve or decide that SA with comment posting cannot be used in this way.

```
Traceback (most recent call last):
Changed files 6
  File "/run_static_analysis.py", line 301, in <module>
    create_or_edit_comment(comment_body_in)
  File "/run_static_analysis.py", line 282, in create_or_edit_comment
    pull_request.create_issue_comment(body=comment_body)
  File "/usr/local/lib/python3.9/dist-packages/github/PullRequest.py", line 456, in create_issue_comment
Repo=p-ranav/argparse pr_num=148 comment_title=Static analysis result
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/dist-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/dist-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"}
Post job cleanup.
```

**Comment by p-ranav** [comment]
[Related](https://github.com/actions/first-interaction/issues/10)?

**Comment by skrobinson** [comment]
To make sure we have a common vocabulary:

- `target` is p-ranav/argparse, aka base
- `merge commit` is the PR source branch's head, aka head

For security, `pull_request` has a read-only token to `target` and cannot write comments in a PR. A possible workaround is to grant a read-write token, but does open attacks as any new PR can include an Action to immediately run and post comments.

`pull_request_target` has a read-write token, but the Action is run with the `target` source, not the `merge commit` source. This is safer, but tells us nothing about PR source code. [A blog post](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) recommends against using `pull_request_target` to check out untrusted PR code for the same reason as above.

Part of the documentation for `pull_request_target` says, "This event allows you to do things like create workflows that label and comment on pull requests based on the contents of the event payload." I'm still trying to understand how to use this idea.

**Comment by skrobinson** [comment]
I believe this PR is ready to go.  StaticAnalysis has added a feature to include comments with PR in public repos and I've switched to using that trigger.

Once this lands, I'll open a new PR with a small janitorial change to try out SA.

**Comment by p-ranav** [comment]
Thank you so much!

**Pull request merged**
